---
title: "Introduction to Importing Data in Python"
author: "Salerno"
date: "2020-03-19"
categories: ["Python", "Data Science", "Programming"]
tags: []
draft: FALSE
banner: img/banners/python.png
---

```{r setup, include=FALSE}
library(reticulate)

path <- file.path(Sys.which("python"))

use_python(python = path)

```

## 1. Importing entire text files

```{python}

# Open a file: file
file = open('c:/blogdown/moby_dick.txt', mode='r')

# Print it
print(file.read())

# Check whether file is closed
print(file.closed)

# Close file
file.close()

# Check whether file is closed
print(file.closed)

```

## 2. Importing text files line by line

```{python}

# Read & print the first 3 lines
with open('c:/blogdown/moby_dick.txt') as file:
    print(file.readline())
    print(file.readline())
    print(file.readline())

```

## 3. Using NumPy to import flat files

```{python}

# Import package
import numpy as np
import matplotlib.pyplot as plt

# Assign filename to variable: file
file = 'c:/blogdown/mnist_kaggle_some_rows.csv'

# Load file as array: digits
digits = np.loadtxt(file, delimiter=',')

# Print datatype of digits
print(type(digits))

# Select and reshape a row
im = digits[21, 1:]
im_sq = np.reshape(im, (28, 28))
# Plot reshaped data (matplotlib.pyplot already loaded as plt)
plt.imshow(im_sq, cmap='Greys', interpolation='nearest')
plt.show()


```

## 4. Customizing your NumPy import


```{python}

# Assign filename: file
file = 'c:/blogdown/seaslug.txt'

# Import file: data
data = np.loadtxt(file, delimiter='\t', dtype=str)

# Print the first element of data
print(data[0])

# Import data as floats and skip the first row: data_float
data_float = np.loadtxt(file, delimiter='\t', dtype=float, skiprows=1)

# Print the 10th element of data_float
print(data_float[9])

# Plot a scatterplot of the data
plt.scatter(data_float[:, 0], data_float[:, 1])
plt.xlabel('time (min.)')
plt.ylabel('percentage of larvae')
plt.show()

```


## 5. Working with mixed datatypes

```{python}

data = 'c:/blogdown/titanic_sub.csv'

data = np.genfromtxt(data, delimiter=',', names=True, dtype=None)

np.shape(data)

print(data['Fare'])

```

## 6. Working with mixed datatypes (2)

```{python}

data = 'c:/blogdown/titanic_sub.csv'

# Import file using np.recfromcsv: d
d = np.recfromcsv(data)

# Print out first three entries of d
print(d[:3])


```

## 7. Using Pandas to import flatfiles as DataFrames

```{python}

# Import pandas as pd
import pandas as pd

# Assign the filename: file
file = 'c:/blogdown/titanic_sub.csv'

# Read the file into a DataFrame: df
df = pd.read_csv(file)

# View the head of the DataFrame
print(df.head())

type(df)


```

## 8. Using pandas to import flat files as DataFrames (2)

```{python}

# Assign the filename: file
file = 'c:/blogdown/titanic_sub.csv'

# Read the first 5 rows of the file into a DataFrame: data
data = pd.read_csv(file, nrows=5, header=None)

# Build a numpy array from the DataFrame: data_array
data_array = np.array(data)

# Print the datatype of data_array to the shell
print(type(data_array))

```


## 9. Customizing your pandas import

```{python}

# Import matplotlib.pyplot as plt
import matplotlib.pyplot as plt

# Assign filename: file
file = 'c:/blogdown/titanic_corrupt.txt'

# Import file: data
data = pd.read_csv(file, sep='\t', comment='#', na_values='Nothing')

# Print the head of the DataFrame
print(data.head())

# Plot 'Age' variable in a histogram
pd.DataFrame.hist(data[['Age']])
plt.xlabel('Age (years)')
plt.ylabel('count')
plt.show()


```

## 10. Not so flat any more

```{python}

import os
wd = os.getcwd()
os.listdir(wd)


```

## 11. Listing sheets in Excel files

```{python}

# Import pandas
import pandas as pd

# Assign spreadsheet filename: file
file = 'c:/blogdown/battledeath.xlsx'

# Load spreadsheet: xls
xls = pd.ExcelFile(file)

# Print sheet names
print(xls.sheet_names)


```


## 12. Importing sheets from Excel files

```{python}

# Assign spreadsheet filename: file
file = 'c:/blogdown/battledeath.xlsx'

# Load spreadsheet: xls
xls = pd.ExcelFile(file)

# Load a sheet into a DataFrame by name: df1
file1 = xls.parse('2004')

# Print the head of the DataFrame df1
print(file1.head())

# Load a sheet into a DataFrame by index: df2
file2 = xls.parse(0)

# Print the head of the DataFrame df2
print(file2.head())

```


## 13. Customizing your spreadsheet import

```{python}

# Assign spreadsheet filename: file
file = 'c:/blogdown/battledeath.xlsx'

# Load spreadsheet: xls
xls = pd.ExcelFile(file)

# Parse the first sheet and rename the columns: df1
df1 = xls.parse(0, skiprows=1, names=('Country', 'AAM due to War (2002)'))

# Print the head of the DataFrame df1
print(df1.head())

# Parse the first column of the second sheet and rename the column: df2
df2 = xls.parse(1, usecols=[0], skiprows=[0], names=['Country'])

# Print the head of the DataFrame df2
print(df2.head())


```

## 14. Importing SAS files

```{python}

# Import sas7bdat package
from sas7bdat import SAS7BDAT 

# Save file to a DataFrame: df_sas
with SAS7BDAT('c:/blogdown/sales.sas7bdat') as file:
    df_sas = file.to_data_frame()

# Print head of DataFrame
print(df_sas.head())

# Plot histogram of DataFrame features (pandas and pyplot already imported)
pd.DataFrame.hist(df_sas[['P']])
plt.ylabel('count')
plt.show()

```


## 15. Importing Stata files

```{python}

# Import pandas
import pandas as pd

# Load Stata file into a pandas DataFrame: df
df = pd.read_stata('c:/blogdown/disarea.dta')

# Print the head of the DataFrame df
print(df.head())

# Plot histogram of one column of the DataFrame
pd.DataFrame.hist(df[['disa10']])
plt.xlabel('Extent of disease')
plt.ylabel('Number of countries')
plt.show()

```


## 16. Using h5py to import HDF5 files

```{python}

# Import packages
import numpy as np
import h5py

# Assign filename: file
file = 'c:/blogdown/L-L1_LOSC_4_V1-1126259446-32.hdf5'

# Load file: data
data = h5py.File(file, 'r')

# Print the datatype of the loaded file
print(type(data))

# Print the keys of the file
for key in data.keys():
    print(key)


```

## 17. Extracting data from your HDF5 file

```{python}

# Import packages
import numpy as np
import h5py

# Assign filename: file
file = 'c:/blogdown/L-L1_LOSC_4_V1-1126259446-32.hdf5'

# Load file: data
data = h5py.File(file, 'r')


# Get the HDF5 group: group
group = data['strain']

# Check out keys of group
for key in group.keys():
    print(key)

# Set variable equal to time series data: strain
strain = data['strain']['Strain'].value

# Set number of time points to sample: num_samples
num_samples = 10000

# Set time vector
time = np.arange(0, 1, 1/num_samples)

# Plot data
plt.plot(time, strain[:num_samples])
plt.xlabel('GPS Time (s)')
plt.ylabel('strain')
plt.show()


```

## 18. Loading .mat files

```{python}

# Import package
import scipy.io

# Load MATLAB file: mat
mat = scipy.io.loadmat('c:/blogdown/albeck_gene_expression.mat')

# Print the datatype type of mat
print(type(mat))


```

## 19. The structure of .mat in Python

```{python}

import scipy.io
import matplotlib.pyplot as plt
import numpy as np


# Load MATLAB file: mat
mat = scipy.io.loadmat('c:/blogdown/albeck_gene_expression.mat')

# Print the keys of the MATLAB dictionary
print(mat.keys())

# Print the type of the value corresponding to the key 'CYratioCyt'
print(type(mat['CYratioCyt']))

# Print the shape of the value corresponding to the key 'CYratioCyt'
print(mat['CYratioCyt'].shape)

# Subset the array and plot it
data = mat['CYratioCyt'][25, 5:]
fig = plt.figure()
plt.plot(data)
plt.xlabel('time (min.)')
plt.ylabel('normalized fluorescence (measure of expression)')
plt.show()

```

## 20. Creating a database engine

```{python}

# Import necessary module
from sqlalchemy import create_engine

file = 'sqlite:///c:/blogdown/Chinook.sqlite'

# Create engine: engine
engine = create_engine(file)

table_names = engine.table_names()
print(table_names)

```

## 21. The Hello World of SQL Queries!

```{python}

# Import packages
from sqlalchemy import create_engine
import pandas as pd

file = 'sqlite:///c:/blogdown/Chinook.sqlite'

# Create engine: engine
engine = create_engine(file)

# Open engine connection: con
con = engine.connect()

# Perform query: rs
rs = con.execute('SELECT * FROM Album')

# Save results of the query to DataFrame: df
df = pd.DataFrame(rs.fetchall())

# Close connection
con.close()

# Print head of DataFrame df
print(df.head())


```

## 22. Customizing the Hello World of SQL Queries

```{python}

# Import packages
from sqlalchemy import create_engine
import pandas as pd

file = 'sqlite:///c:/blogdown/Chinook.sqlite'

# Create engine: engine
engine = create_engine(file)

# Open engine in context manager
# Perform query and save results to DataFrame: df
with engine.connect() as con:
    rs = con.execute("SELECT LastName, Title FROM Employee")
    df = pd.DataFrame(rs.fetchmany(size=3))
    df.columns = rs.keys()

# Print the length of the DataFrame df
print(len(df))

# Print the head of the DataFrame df
print(df.head())


```

## 23. Filtering your database records using SQL's WHERE

```{python}

# Import packages
from sqlalchemy import create_engine
import pandas as pd

file = 'sqlite:///c:/blogdown/Chinook.sqlite'

# Create engine: engine
engine = create_engine(file)

# Open engine in context manager
# Perform query and save results to DataFrame: df
with engine.connect() as con:
    rs = con.execute("SELECT * FROM Employee WHERE EmployeeId >= 6")
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print the head of the DataFrame df
print(df.head())

```

## 24. Ordering your SQL records with ORDER BY

```{python}


# Import packages
from sqlalchemy import create_engine
import pandas as pd

file = 'sqlite:///c:/blogdown/Chinook.sqlite'

# Create engine: engine
engine = create_engine(file)

# Open engine in context manager
with engine.connect() as con:
    rs = con.execute("SELECT * FROM Employee ORDER BY BirthDate")
    df = pd.DataFrame(rs.fetchall())

    # Set the DataFrame's column names
    df.columns = rs.keys()

# Print head of DataFrame
print(df.head())


```

## 25. Pandas and The Hello World of SQL Queries!

```{python}


# Import packages
from sqlalchemy import create_engine
import pandas as pd

file = 'sqlite:///c:/blogdown/Chinook.sqlite'

# Create engine: engine
engine = create_engine(file)

# Execute query and store records in DataFrame: df
df = pd.read_sql_query("SELECT * FROM Album", engine)

# Print head of DataFrame
print(df.head())

# Open engine in context manager and store query result in df1
with engine.connect() as con:
    rs = con.execute("SELECT * FROM Album")
    df1 = pd.DataFrame(rs.fetchall())
    df1.columns = rs.keys()

# Confirm that both methods yield the same result
print(df.equals(df1))

```

## 26. Pandas for more complex querying

```{python}

# Import packages
from sqlalchemy import create_engine
import pandas as pd

file = 'sqlite:///c:/blogdown/Chinook.sqlite'

# Create engine: engine
engine = create_engine(file)


# Execute query and store records in DataFrame: df
df = pd.read_sql_query("SELECT * FROM Employee WHERE EmployeeId >= 6 ORDER BY BirthDate", engine)

# Print head of DataFrame
print(df.head())



```

## 27. The power of SQL lies in relationships between tables: INNER JOIN

```{python}

# Import packages
from sqlalchemy import create_engine
import pandas as pd

file = 'sqlite:///c:/blogdown/Chinook.sqlite'

# Create engine: engine
engine = create_engine(file)

# Open engine in context manager
# Perform query and save results to DataFrame: df
with engine.connect() as con:
    rs = con.execute("SELECT Title, Name FROM Album INNER JOIN Artist on Album.ArtistID = Artist.ArtistID")
    df = pd.DataFrame(rs.fetchall())
    df.columns = rs.keys()

# Print head of DataFrame df
print(df.head())



```

## 28. Filtering your INNER JOIN

```{python}


# Import packages
from sqlalchemy import create_engine
import pandas as pd

file = 'sqlite:///c:/blogdown/Chinook.sqlite'

# Create engine: engine
engine = create_engine(file)

# Execute query and store records in DataFrame: df
df = pd.read_sql_query("SELECT * FROM PlaylistTrack INNER JOIN Track on PlaylistTrack.TrackId = Track.TrackId WHERE Milliseconds < 250000", engine)

# Print head of DataFrame
print(df.head())



```

