baseurl = "http://datafintechsolutions.com/"
title = "DFS"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "andresalerno"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-154740345-1"

# Define the number of posts per page
paginate = 10

ignoreFiles = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[menu]

# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="blog"
    name = "Blog"
    url  = "/blog/"
    weight = 2

#[[menu.main]]
#    identifier = "faq"
#    name = "FAQ"
#    url  = "/faq/"
#    weight = 3

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "/contact/"
    weight = 3

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/andresalerno"
    pre = "<i class='fab fa-2x fa-github'></i>"
    customClass = "github"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "https://www.facebook.com/aspartnersconsultoria/?ref=bookmarks"
    pre = "<i class='fab fa-2x fa-facebook'></i>"
    customClass = "facebook"

[[menu.topbar]]
    weight = 3
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/andresalerno/"
    pre = "<i class='fab fa-linkedin-in'></i>"
    customClass = "lindekin"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto: andresalerno22@gmail.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"
    customClass = "email"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    mainSections = ["blog"]
    defaultDescription = "Site template made by devcows using hugo"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = "AIzaSyAIUDnabrE-98Y_3EWdNun6iNBED38BsV0"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "andresalerno22@gmail.com"
    contact_form_ajax = false

    about_us = "<p>A Data Fintech Solutions is a company that has in her DNA the use the most consistent tech and financial tools associated with the most recent tech solutions.</p>"
    copyright = "Copyright (c) 2019 - 2020, Data Fintech Solutions; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo.png"
    logo_small = "img/logo-small.png"
    address = """<p class="text-uppercase"><strong>Data Fintech Solutions</strong>
        <br>
        <br>São José dos Campos
        <br>
        <strong>Parayba Valley</strong>
      </p>
      """
    latitude = "-23.2209236"
    longitude = "-45.9111879"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on <span>+55 11 9 9600-0630</span> or <span>andresalerno22@gmail.com</span>.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "What they say about our solutions"
    subtitle = ""

[params.see_more]
    enable = false
    icon = "far fa-file-alt"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our clients and partners"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Blog"
    subtitle = "Here you can find our success cases, recent studies and much more. We not only want you to gain knowledge here, but we encourage you that in this space you get valuable information can be exchanged"
