---
title: "Correlation and Regression"
author: "Salerno"
date: '2020-01-19'
slug: correlation-and-regression
tags: ["Statistic", "Modeling", "KNN"]
categories: R Programming
draft: FALSE
banner: img/banners/banner-5.png
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(collapse = TRUE, warnings = FALSE, echo = TRUE)

library(tidyverse)

```

```{r}

path <- "C:/Users/andre/OneDrive/Área de Trabalho/salerno/blogdown/datasets/ncbirths"

path <- paste0(path, "/ncbirths.csv")

data <- read.csv(path, stringsAsFactors = FALSE)

```

```{r}
dim(data)
```

```{r}

names(data)

```

```{r}

library(ggplot2)

ggplot(data = data, aes(y = BirthWeightOz, x = Weeks)) +
geom_point()

```

```{r}
# Boxplot of weight vs. weeks
ggplot(data = data, 
       aes(x = cut(Weeks, breaks = 5), y = BirthWeightOz)) + 
  geom_boxplot()

```

```{r}

library(tidyverse)
## computing correlation

data %>%
  summarize(N = n(), r = cor(BirthWeightOz, MomAge))

# Compute correlation for all non-missing pairs
data %>%
  summarize(N = n(), r = cor(BirthWeightOz, MomAge, use = "pairwise.complete.obs"))

```



```{r}
library(openintro)

ggplot(data = mammals, aes(y = BrainWt, x = BodyWt)) +
    geom_point()

# Scatterplot with coord_trans()
ggplot(data = mammals, aes(y = BrainWt, x = BodyWt)) +
  geom_point() + 
  coord_trans(x = "log10", y = "log10")

# Scatterplot with scale_x_log10() and scale_y_log10()
ggplot(data = mammals, aes(x = BodyWt, y = BrainWt)) +
  geom_point() +
  scale_x_log10() + 
  scale_y_log10()

```

```{r}

# Correlation among mammals, with and without log
mammals %>%
  summarize(N = n(), 
            r = cor(BodyWt, BrainWt), 
            r_log = cor(log(BodyWt), log(BrainWt)))
```



```{r}
library(tidyverse)
ggplot(data = mlbBat10, aes(y = SLG, x = OBP)) +
    geom_point()

# identifying outliers
# Filter for AB greater than or equal to 200
ab_gt_200 <- mlbBat10 %>%
  filter(AB >= 200) 

# Scatterplot of SLG vs. OBP
ggplot(ab_gt_200, aes(x = OBP, y = SLG)) +
  geom_point()

# Identify the outlying player
ab_gt_200 %>%
  filter(OBP < 0.2)

```

```{r}


# Correlation for all baseball players
mlbBat10 %>%
  summarize(N = n(), r = cor(OBP, SLG))

```

```{r}

# Run this and look at the plot
mlbBat10 %>% 
    filter(AB > 200) %>%
    ggplot(aes(x = OBP, y = SLG)) + 
    geom_point()

# Correlation for all players with at least 200 ABs
mlbBat10 %>%
  filter(AB >= 200) %>%
  summarize(N = n(), r = cor(OBP, SLG))

```



```{r}

# Run this and look at the plot
ggplot(data = bdims, aes(x = hgt, y = wgt, color = factor(sex))) +
  geom_point() 

# Correlation of body dimensions
bdims %>%
  group_by(sex) %>%
  summarize(N = n(), r = cor(hgt, wgt))


```

```{r}

ggplot(data = smoking, aes(y = amtWeekdays, x = age)) +
      geom_point()

```

```{r}

path1 <- "C:/Users/andre/OneDrive/Área de Trabalho/salerno/blogdown/datasets/anscombe"

path1 <- paste0(path1, "/anscombe.csv")

anscombe <- read.csv(path1, stringsAsFactors = FALSE, sep = ";")


# Compute properties of Anscombe
anscombe %>%
  group_by(set) %>%
  summarize(
    N = n(), 
    mean_of_x = mean(x), 
    std_dev_of_x = sd(x), 
    mean_of_y = mean(y), 
    std_dev_of_y = sd(y), 
    correlation_between_x_and_y = cor(x, y)
  )

```

