---
title: R Packages for Regression
author: Salerno
date: '2019-12-23'
slug: r-packages-for-regression
categories:
  - R
  - programming
tags:
  - regression
draft: FALSE
banner: img/banners/banner-5.png
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, warnings = FALSE, echo = TRUE)
```

# R Packages for Regression

For this post we will present some valuable R packages for using in regression studies. Check it out!

## `stats`

Package very useful for statistical calculations and random number generations.

Below you can find the most useful function in regression area:

- `lm()`: it is used to fit linear models

- `summary.lm()`: thsi function returns a summary for linear model fits

- `coef()`: it is possible obtain the coefficients from modeling functions

- `fitted()`: return fitted values

- `formula()`: extract formula

- `predict()`: used to predicts values based on linear models

- `residuals()`: this function extracts model residuals

- `confint()`: this function computes a confidence intervals

- `deviance()`: it returns the deviance of a fitted model

- `influence.measures()`: this function can be used to compute some of the regression diagnostics for linear and GLM

- `lm.influence()`: iit provides some diagnostics for checking the quality of the regression

- `ls.diag()`: it computes the basic statistics, like standard errors, t-values, p-values and etc

- `glm()`: it is used to fit GLM models

- `loess()`: this function fit polynomial surface


